In [1]:
import numpy as np


In [2]:
with open('one_array.npy','wb') as f:
    np.save(f,np.array([1,2]))

In [3]:
np.load('one_array.npy')

array([1, 2])

In [4]:
with open('test.npy','wb') as f:
    np.save(f,np.array([1,2]))
    np.save(f,np.array([3,4]))
    np.save(f,np.array([5,6]))
    np.save(f,np.array([7,8]))

In [6]:
with open('test.npy','rb') as f:
    a = np.load(f)
    b = np.load(f)
    c = np.load(f)
    d = np.load(f)
print(a,b,c,d)   

[1 2] [3 4] [5 6] [7 8]


In [10]:
x = np.arange(10)
y = np.array([1,2,3])
z = np.random.rand(10)

with open('multi_array.npz','wb') as f:
    np.savez(f,array1=x,array2=y,array3=z)

In [12]:
npyzfile = np.load('multi_array.npz')
type(npyzfile)


numpy.lib.npyio.NpzFile

In [13]:
npyzfile.files

['array1', 'array2', 'array3']

In [15]:
print(npyzfile['array1'])
print(npyzfile['array2'])
print(npyzfile['array3'])

[0 1 2 3 4 5 6 7 8 9]
[1 2 3]
[0.53199879 0.54194317 0.24046868 0.02879518 0.31963155 0.93648814
 0.0650361  0.65203206 0.66513983 0.30113341]


In [16]:
x = y = z = np.arange(0.0,5.0,1.0)
x

array([0., 1., 2., 3., 4.])

In [17]:
y = np.arange(10).reshape(2,5)
y

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [18]:
np.savetxt('test.out',[x],delimiter=',')

In [ ]:
# %load test.out
0.000000000000000000e+00,1.000000000000000000e+00,2.000000000000000000e+00,3.000000000000000000e+00,4.000000000000000000e+00


In [20]:
np.savetxt('test.gz',[x],delimiter=',')

In [29]:
np.savetxt('test.csv',y,delimiter=',')

In [ ]:
# %load test.csv
0.000000000000000000e+00,1.000000000000000000e+00,2.000000000000000000e+00,3.000000000000000000e+00,4.000000000000000000e+00


In [23]:
np.savetxt('test.out',x,fmt='%1.4e',delimiter=',',header='this is,\n header ',footer='this is footer')

In [ ]:
# %load test.out
# this is,
#  header 
0.0000e+00
1.0000e+00
2.0000e+00
3.0000e+00
4.0000e+00
# this is footer


In [25]:
np.loadtxt('test.out',delimiter=',',dtype='f4')

array([0., 1., 2., 3., 4.], dtype=float32)

In [30]:
np.genfromtxt('test.csv',delimiter=',')

array([[0., 1., 2., 3., 4.],
       [5., 6., 7., 8., 9.]])

In [31]:
np.genfromtxt('test.gz',delimiter=',')

array([0., 1., 2., 3., 4.])

In [33]:
np.genfromtxt(["1","2","abc","4","5"])

array([ 1.,  2., nan,  4.,  5.])

In [35]:
from io import StringIO

data = u"  1  2  3\n  4  5 67\n890123  4"
np.genfromtxt(StringIO(data),delimiter=3)

array([[  1.,   2.,   3.],
       [  4.,   5.,  67.],
       [890., 123.,   4.]])

In [36]:
data = u"123456789\n   4  7 9\n   4567 9"
np.genfromtxt(StringIO(data),delimiter=(4,3,2))

array([[1234.,  567.,   89.],
       [   4.,    7.,    9.],
       [   4.,  567.,    9.]])

In [37]:
data = u"1, 2 , 4\n 4, 5, 6"
np.genfromtxt(StringIO(data),delimiter=',',autostrip=True)

array([[1., 2., 4.],
       [4., 5., 6.]])

In [39]:
np.genfromtxt("test.out",comments="#")

array([0., 1., 2., 3., 4.])

In [43]:
np.genfromtxt("test.out",comments=None,skip_footer=1,skip_header=2)

array([0., 1., 2., 3., 4.])

In [ ]:
# %load names.txt
a,b,c
1,2,3
4,5,6
7,8,9

In [52]:
np.genfromtxt("names.txt",delimiter=",",names=True)

array([(1., 2., 3.), (4., 5., 6.), (7., 8., 9.)],
      dtype=[('a', '<f8'), ('b', '<f8'), ('c', '<f8')])

In [53]:
data = StringIO("1 2 3\n 4 5 6")
np.genfromtxt(data, names= "a,b,c")

array([(1., 2., 3.), (4., 5., 6.)],
      dtype=[('a', '<f8'), ('b', '<f8'), ('c', '<f8')])

In [54]:
a = u"1,2,3,4,5\n6,7,8,9,10"
np.genfromtxt(StringIO(a),delimiter=',',names="a,b,c",usecols=("a","c"))

array([(1., 3.), (6., 8.)], dtype=[('a', '<f8'), ('c', '<f8')])

In [59]:
a = u"1 2 3 4 5\n6 7 8 9 10"
np.genfromtxt(StringIO(a), names="a, b, c", usecols=(1, -1))

IndexError: list index out of range

In [60]:
a = u"1 2 3 4 5\n6 7 8 9 10"
np.genfromtxt(StringIO(a), usecols=(1, -1))

array([[ 2.,  5.],
       [ 7., 10.]])

In [62]:
a = StringIO("1 2 3\n 4 5 6")
np.genfromtxt(a,dtype=(int, float, int))

array([(1, 2., 3), (4, 5., 6)],
      dtype=[('f0', '<i8'), ('f1', '<f8'), ('f2', '<i8')])

In [64]:
a = StringIO("1 2 3\n 4 5 6")
np.genfromtxt(a,dtype=(int,float,int),defaultfmt="var_%i")

array([(1, 2., 3), (4, 5., 6)],
      dtype=[('var_0', '<i8'), ('var_1', '<f8'), ('var_2', '<i8')])

In [65]:
a = u", 2, 3\n4, ,"
np.genfromtxt(StringIO(a),delimiter=",",filling_values=np.nan)

array([[nan,  2.,  3.],
       [ 4., nan, nan]])

In [66]:
a = u"N/A, 2, 3, ???"
np.genfromtxt(StringIO(a),delimiter=',',
              missing_values=["N/A","N/A","N/A","???"],
              filling_values=[0,0,0,-999])

array([   0.,    2.,    3., -999.])

In [67]:
a = u"1, , \n , 5, 6"
np.genfromtxt(StringIO(a),delimiter=',',dtype="int, float, str")

array([( 1, nan, ''), (-1,  5., '')],
      dtype=[('f0', '<i8'), ('f1', '<f8'), ('f2', '<U')])

In [69]:
np.genfromtxt("transform.txt",delimiter=',',dtype="i8,i8,U3,U3")

array([(1, 2, 'Yes', '87%'), (3, 4, 'No', '3%'), (5, 6, 'Yes', '55%')],
      dtype=[('f0', '<i8'), ('f1', '<i8'), ('f2', '<U3'), ('f3', '<U3')])

In [70]:
def trans(s):
    if s== b'Yes':
        return 1
    else:
        return 0

In [71]:
def conversion(x):
    return float(x.strip(b"%"))/100

In [72]:
np.genfromtxt("transform.txt",delimiter=',',converters={2:trans,3:conversion})

array([(1., 2., 1, 0.87), (3., 4., 0, 0.03), (5., 6., 1, 0.55)],
      dtype=[('f0', '<f8'), ('f1', '<f8'), ('f2', '<i8'), ('f3', '<f8')])