In [31]:
import numpy as np
import warnings

In [2]:
np.add(1.0,3.0)

4.0

In [3]:
a = np.array([1,2,3,4,5])
b = np.array([2,2,2,2,2])
a+b

array([3, 4, 5, 6, 7])

In [4]:
np.add(a,b)

array([3, 4, 5, 6, 7])

In [5]:
a-b

array([-1,  0,  1,  2,  3])

In [6]:
a*b

array([ 2,  4,  6,  8, 10])

In [7]:
a/b

array([0.5, 1. , 1.5, 2. , 2.5])

In [8]:
a%b

array([1, 0, 1, 0, 1])

In [13]:
c = np.arange(10)
d =3
c

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
c*d

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [11]:
e = np.random.randint(1,10,20).reshape(2,10)
e

array([[8, 1, 7, 4, 1, 8, 6, 9, 5, 5],
       [6, 2, 5, 9, 1, 9, 3, 6, 8, 6]])

In [12]:
c+e

array([[ 8,  2,  9,  7,  5, 13, 12, 16, 13, 14],
       [ 6,  3,  7, 12,  5, 14,  9, 13, 16, 15]])

In [15]:
a = np.arange(10).reshape(2,5)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [16]:
a.sum()

45

In [17]:
np.sum(a,axis=0)

array([ 5,  7,  9, 11, 13])

In [18]:
np.power(2,3)

8

In [19]:
e**c

array([[       1,        1,       49,       64,        1,    32768,
           46656,  4782969,   390625,  1953125],
       [       1,        2,       25,      729,        1,    59049,
             729,   279936, 16777216, 10077696]])

In [20]:
np.sqrt(4)

2.0

In [22]:
np.sqrt(a)

array([[0.        , 1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ]])

In [23]:
np.e

2.718281828459045

In [24]:
np.exp(1)

2.718281828459045

In [26]:
np.exp(np.arange(5))

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [29]:
np.log10(np.array([1,10,100,1000,10000]))

array([0., 1., 2., 3., 4.])

In [30]:
np.log(9)/np.log(3)

2.0

In [32]:
warnings.filterwarnings('ignore')

In [33]:
np.log([-1,1,2])

array([       nan, 0.        , 0.69314718])

In [35]:
a = np.array([1.65,1.55,-3.57,2.0])
a

array([ 1.65,  1.55, -3.57,  2.  ])

In [36]:
np.round(a,decimals=1)

array([ 1.6,  1.6, -3.6,  2. ])

In [37]:
np.rint(a)

array([ 2.,  2., -4.,  2.])

In [38]:
np.trunc(a)

array([ 1.,  1., -3.,  2.])

In [39]:
np.floor(a)

array([ 1.,  1., -4.,  2.])

In [41]:
np.ceil(a)

array([ 2.,  2., -3.,  2.])

In [42]:
np.fix(a)

array([ 1.,  1., -3.,  2.])

In [43]:
np.abs(a)

array([1.65, 1.55, 3.57, 2.  ])

In [45]:
np.abs(1+2j)

2.23606797749979

In [46]:
np.fabs(1+2j)

TypeError: ufunc 'fabs' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''