In [1]:
import numpy as np

In [2]:
np.isnan(np.array([1.0,np.nan,3.0]))

array([False,  True, False])

In [3]:
np.isfinite(1.0)

True

In [4]:
np.isfinite(np.nan)

False

In [5]:
np.isinf([np.inf,-np.inf,1.0,np.nan,np.PINF])

array([ True,  True, False, False,  True])

In [6]:
np.isposinf(np.PINF)

True

In [7]:
np.isneginf(np.NINF),np.isneginf(np.nan)

(True, False)

In [8]:
np.isnat(np.array(["NaT","2020-06-26"],dtype="datetime64[ns]"))

array([ True, False])

In [10]:
a = np.array([1,2,3])

In [11]:
np.isscalar(a[2])

True

In [12]:
np.isscalar(a)

False

In [13]:
np.isscalar(np.pi)

True

In [14]:
np.isscalar(np.array(3.0))

False

In [18]:
b = np.array([1+1j,0+0j,4.5,3,2,2j])
b

array([1. +1.j, 0. +0.j, 4.5+0.j, 3. +0.j, 2. +0.j, 0. +2.j])

In [19]:
np.isreal(b)

array([False,  True,  True,  True,  True, False])

In [20]:
np.iscomplex(b)

array([ True, False, False, False, False,  True])

In [21]:
np.iscomplexobj(b)

True

In [22]:
np.isrealobj(b)

False

In [23]:
np.isrealobj(np.array([1,2.0,3.1]))

True

In [24]:
np.array_equal(np.array([1,2,3]),np.array([1,2,3]))

True

In [26]:
np.array_equal(np.array([1,2,3]),np.array([1,2,5]))

False

In [27]:
np.array_equiv(np.array([1,2,3]),np.array([1,2,3]))

True

In [30]:
np.array_equiv(np.array([1,2,3]),np.array([1,2,5]))

False

In [29]:
np.array_equiv(np.array([1,2,3]),np.array([[1,2,3],[1,2,3]]))

True

In [34]:
np.array_equiv(np.array([1,2,3]),np.array([1,2]))

False

In [33]:
np.array_equiv(np.array([1,1,1]),np.array([1]))

True

In [35]:
np.equal(np.array([1,2,3]),np.array([1,2,3]))

array([ True,  True,  True])

In [38]:
np.equal(np.array([1,1,1]),np.ones(1))

array([ True,  True,  True])

In [41]:
np.not_equal([1,2],[[1,3],[1,4]])

array([[False,  True],
       [False,  True]])

In [42]:
x = np.array([True,True,False,False])
y = np.array([True,False,True,False])

In [43]:
np.logical_and(x,y)

array([ True, False, False, False])

In [44]:
np.logical_or(x,y)

array([ True,  True,  True, False])

In [45]:
np.logical_not(x)

array([False, False,  True,  True])

In [46]:
np.logical_xor(x,y)

array([False,  True,  True, False])

In [47]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [48]:
np.logical_and(a>1,a<4)

array([False, False,  True,  True, False])

In [49]:
np.all([-1,np.nan,5])

True

In [50]:
np.all([-1,4,0])

False

In [51]:
np.any([[True,False],[True,True]])

True

In [54]:
np.any([[True,False],[False,False]],axis=0)

array([ True, False])